# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# DELETED relative_permalinks: true

# Setup
title: Contact Mapping
email: hello@contactmapping.com
tagline:             'Humanize Your Addressbook'
description:         'Contact Mapping is an app that will enable you to humanize your address book.  You will be able to match the human you want to keep in touch with with the contact in your address book.'
url:                 
baseurl:             '/lanyon/'
paginate:            5

# About/contact
author:
  name:              Aliza
#  url:               https://twitter.com/mdo
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
